# Generated by Django 5.0.7 on 2024-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_spelization',
            new_name='doc_specilization',
        ),
    ]
